//对外暴露配置路由
export const  constantRoute = [
     {
            path:'/login',
            component:()=>import('@/views/login/index.vue'),
            name:'login',
            meta:{title:'登录',hidden:true,icon:'DataLine'},
            
        },
        {
            path:'/',
            component:()=>import('@/layout/index.vue'),
            name:'layout',
            meta:{title:'layout',icon:'Postcard'},
            redirect:'/home',
            children:[
                {
                    path:'/home',
                    component:()=>import('@/views/home/index.vue'),
                    name:'home',
                    meta:{title:'首页',icon:'HomeFilled'}
                }
            ]
        },
        {
            path:'/screen',
            component:()=>import('@/views/screen/index.vue'),
            name:'screen',
            meta:{title:'数据大屏',icon:'Platform',hidden:false},
        },
        {
            path:'/acl',
            component:()=>import('@/layout/index.vue'),
            name:'Acl',
            meta:{title:'权限管理',icon:'Lock',hidden:false},
            children:[
                {
                    path:'/acl/user',
                    component:()=>import('@/views/acl/user/index.vue'),
                    name:'user',
                    meta:{title:'用户管理',icon:'User',hidden:false}
                },
                {
                    path:'/acl/role',
                    component:()=>import('@/views/acl/role/index.vue'),
                    name:'role',
                    meta:{title:'角色管理',icon:'CreditCard',hidden:false}
                },
                {
                    path:'/acl/permission',
                    component:()=>import('@/views/acl/permission/index.vue'),
                    name:'permission',
                    meta:{title:'权限管理',icon:'Files',hidden:false}
                }
            ]
        },
        {
            path:'/product',
            component:()=>import('@/layout/index.vue'),
            name:'Product',
            meta:{title:'商品管理',icon:'Goods',hidden:false},
            children:[
                {
                    path:'/product/sku',
                    component:()=>import('@/views/product/sku/index.vue'),
                    name:'Sku',
                    meta:{title:'sku管理',icon:'Grid',hidden:false}
                },
                {
                    path:'/product/attr',
                    component:()=>import('@/views/product/attr/index.vue'),
                    name:'Attr',
                    meta:{title:'attr管理',icon:'Monitor',hidden:false}
                },
                {
                    path:'/product/spu',
                    component:()=>import('@/views/product/spu/index.vue'),
                    name:'Spu',
                    meta:{title:'spu管理',icon:'Paperclip',hidden:false}
                },
                {
                    path:'/product/trademark',
                    component:()=>import('@/views/product/trademark/index.vue'),
                    name:'Trademark',
                    meta:{title:'trademark管理',icon:'Reading',hidden:false}
                }
            ]
        },
        {
            path:'/404',
            component:()=>import('@/views/404/index.vue'),
            name:'404',
            meta:{title:'404',icon:'Operation',hidden:true},
            hidden:true
        },
        {
            path:'/:pathMatch(.*)*',
            redirect:'/404',
            name:'Any',
            meta:{title:'任意路由',icon:'Stopwatch',hidden:true},
        },

]